### ISSUE TITLE
Convert DNS records config format

### ISSUE THREAD

**Issue by mxmehl** [mxmehl/inwx-dns-recordmaster#2]
The current format is somewhat nasty and hacky. Also, the domain is derived from the file name, that's strange.

We could read all files in the records config folder, which are baseusing this format:

```yaml
# All definitions for example.com and its subdomains
- domain: example.com
  records:
    # Records configuring example.com
    root:
    - type: A
      content: "192.168.13.37"
    - type: AAAA
      content: "1337:e5e1::1"
    - type: MX
      content: mail.mailprovider.tld
      prio: 10
    - type: NS
      content: ns.inwx.de
      ttl: 86400
    - type: NS
      content: ns2.inwx.de
      ttl: 86400
    - type: NS
      content: ns3.inwx.eu
      ttl: 86400
    subdomains:
      # Records configuring subdomains of example.com
      # *.example.com
      "*":
        - type: A
          content: "192.168.13.37"
        - type: AAAA
          content: "1337:e5e1::1"
      # test.example.com
      test:
        - type: CNAME
          content: cloudprovider.tld
          ttl: 300
```

We could allow all kinds of files, also multiple domains in one file, but include a check that avoid that a domain is configured multiple times.
