### ISSUE TITLE
Syntax checks: type and content have to be present

### ISSUE THREAD

**Issue by mxmehl** [mxmehl/inwx-dns-recordmaster#8]
This shouldn't be allowed:

```yaml
example.com:
  root:
    - type: A
  subdomains:
    www:
      - type: A
```
